### ISSUE TITLE
Pylons txs spam restriction through validator

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/pylons#1]
this request is khanh - level task. **It will bring huge money to Notional**.

request from Pylons team is as following: 

1. write code for validator to help filter spam txs (don't want to add too many txs to a block) (1 to 2 txs per block from 1 address)
2. spam attack current pylons testnet (preferably bring it down)

**Deadline**: 1 week

**Comment by catShaark** [comment]
I think this can be done by moding tx reaper in tendermint tx pool

**Comment by nghuyenthevinh2000** [comment]
need a brief description of how modding will happend?
